'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property back() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Background() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property bg_pattern() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("bg_pattern", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property bug_tracker_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("bug_tracker_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Chart() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Chart", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property clock() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("clock", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property close_btn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("close_btn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property details_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("details_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property file_explorer_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("file_explorer_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property five() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("five", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property GridView() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GridView", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property hunt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("hunt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icon() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ie() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ie", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ie_logo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ie_logo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property img1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("img1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property img2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("img2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property img3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("img3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property img4() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("img4", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property img5() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("img5", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property level1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("level1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property level2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("level2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property level3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("level3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property list_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("list_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ListView() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ListView", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property magnifier_bg() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("magnifier_bg", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property magnifier_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("magnifier_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property maximize_btn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("maximize_btn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property minimize_btn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("minimize_btn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property movieLab_bg() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("movieLab_bg", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property panorama() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("panorama", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property qsf_bg() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("qsf_bg", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property qsf_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("qsf_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Rss_reader_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Rss_reader_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Scheduler() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Scheduler", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property settings() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property store() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("store", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ThViewer_bg() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ThViewer_bg", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ThViewer_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ThViewer_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property tiles_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("tiles_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property TreeView() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("TreeView", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property TV_search() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("TV_search", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property vsb_bg() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("vsb_bg", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property vsb_icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("vsb_icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
	
	    Friend Shared ReadOnly Property AllTelerikProducts() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AllTelerikProducts", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
