Imports System.Linq
Imports System.Text

Namespace Telerik.Examples.WinControls.ChartView.SmartLabels
	Public Class DataModel
		Public Function GetPieData() As List(Of KeyValuePair(Of Double, Object))
			Dim data As New List(Of KeyValuePair(Of Double, Object))()

			data.Add(New KeyValuePair(Of Double, Object)(46, "Samsung"))
			data.Add(New KeyValuePair(Of Double, Object)(43.5, "Apple"))
			data.Add(New KeyValuePair(Of Double, Object)(19, "RIM"))
			data.Add(New KeyValuePair(Of Double, Object)(15, "Huawei"))
			data.Add(New KeyValuePair(Of Double, Object)(14, "Other"))
			data.Add(New KeyValuePair(Of Double, Object)(12, "Siemens"))
			data.Add(New KeyValuePair(Of Double, Object)(11.5, "Panasonic"))
			data.Add(New KeyValuePair(Of Double, Object)(8, "Nokia"))
			data.Add(New KeyValuePair(Of Double, Object)(6.5, "Sony"))
			data.Add(New KeyValuePair(Of Double, Object)(3.5, "Fujitsu"))
			data.Add(New KeyValuePair(Of Double, Object)(3, "HTC"))
			data.Add(New KeyValuePair(Of Double, Object)(2, "Motorola"))

			Return data
		End Function

		Public Function GetBarData() As List(Of KeyValuePair(Of Double, Object))
			Dim data As New List(Of KeyValuePair(Of Double, Object))()

			Dim point As New KeyValuePair(Of Double, Object)(20.55, "Samsung")
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(20.2, "Apple")
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(19, "Other")
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(15, "Sony")
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(14, "HTC")
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(5.7, "Blackberry")
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(5.55, "Nokia")
			data.Add(point)

			Return data
		End Function

		Public Function GetLineOneData() As List(Of KeyValuePair(Of Double, Object))
			Dim data As New List(Of KeyValuePair(Of Double, Object))()

			Dim point As New KeyValuePair(Of Double, Object)(400, 2007)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(550, 2008)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(740, 2009)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(940, 2010)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1170, 2011)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1388, 2012)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1540, 2013)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1720, 2014)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(2000, 2015)
			data.Add(point)

			Return data
		End Function

		Public Function GetLineTwoData() As List(Of KeyValuePair(Of Double, Object))
			Dim data As New List(Of KeyValuePair(Of Double, Object))()

			Dim point As New KeyValuePair(Of Double, Object)(1120, 2007)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1240, 2008)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1350, 2009)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1400, 2010)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1490, 2011)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1535, 2012)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1610, 2013)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1680, 2014)
			data.Add(point)
			point = New KeyValuePair(Of Double, Object)(1700, 2015)
			data.Add(point)

			Return data
		End Function

		Public Function GetScatterData() As List(Of KeyValuePair(Of Double, Double))
			Dim data As New List(Of KeyValuePair(Of Double, Double))()

			Dim point As New KeyValuePair(Of Double, Double)(99, 36)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(57, 11)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(51, 34)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(22, 50)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(95, 35)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(30, 26)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(31, 78)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(79, 87)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(57, 57)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(21, 101)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(20, 66)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(66, 20)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(70, 64)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(91, 72)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(38, 32)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(94, 48)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(20, 51)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(79, 65)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(81, 23)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(60, 43)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(72, 65)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(58, 50)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(36, 80)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(20, 69)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(89, 13)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(34, 90)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(37, 40)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(99, 17)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(88, 81)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(79, 91)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(66, 37)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(26, 96)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(75, 95)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(45, 69)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(84, 98)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(21, 17)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(15, 99)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(51, 20)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(67, 77)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(42, 71)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(16, 29)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(17, 48)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(22, 26)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(23, 52)
			data.Add(point)
			point = New KeyValuePair(Of Double, Double)(99, 34)
			data.Add(point)

			Return data
		End Function
	End Class
End Namespace