Namespace Telerik.Examples.WinControls.GridView.ManipulateData.ValidateChanges
	Partial Public Class Form1
		''' <summary> 
		''' Required designer variable.
		''' </summary>
		Private components As System.ComponentModel.IContainer = Nothing

		''' <summary> 
		''' Clean up any resources being used.
		''' </summary>
		''' <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			If disposing AndAlso (components IsNot Nothing) Then
				components.Dispose()
			End If
			MyBase.Dispose(disposing)
		End Sub

		#Region "Component Designer generated code"

		''' <summary> 
		''' Required method for Designer support - do not modify 
		''' the contents of this method with the code editor.
		''' </summary>
		Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container()
            Dim GridViewDecimalColumn1 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn()
            Dim GridViewDecimalColumn2 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn()
            Dim GridViewDecimalColumn3 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn()
            Dim GridViewDecimalColumn4 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn()
            Dim GridViewDecimalColumn5 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn()
            Me.radGridView1 = New Telerik.WinControls.UI.RadGridView()
            Me.orderDetailsBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.northwindDataSet = New Telerik.Examples.WinControls.DataSources.NorthwindDataSet()
            Me.order_DetailsTableAdapter = New Telerik.Examples.WinControls.DataSources.NorthwindDataSetTableAdapters.Order_DetailsTableAdapter()
            Me.radGroupBox1 = New Telerik.WinControls.UI.RadGroupBox()
            Me.radLabel1 = New Telerik.WinControls.UI.RadLabel()
            Me.radSpinEditor2 = New Telerik.WinControls.UI.RadSpinEditor()
            Me.radSpinEditor1 = New Telerik.WinControls.UI.RadSpinEditor()
            Me.radComboBox3 = New Telerik.WinControls.UI.RadDropDownList()
            Me.radComboBox2 = New Telerik.WinControls.UI.RadDropDownList()
            Me.radComboBox1 = New Telerik.WinControls.UI.RadDropDownList()
            CType(Me.settingsPanel, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.settingsPanel.SuspendLayout()
            CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.radGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.orderDetailsBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.northwindDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.radGroupBox1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.radGroupBox1.SuspendLayout()
            CType(Me.radLabel1, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.radSpinEditor2, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.radSpinEditor1, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.radComboBox3, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.radComboBox2, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.radComboBox1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.SuspendLayout()
            '
            'settingsPanel
            '
            Me.settingsPanel.Controls.Add(Me.radGroupBox1)
            Me.settingsPanel.Location = New System.Drawing.Point(844, 1)
            Me.settingsPanel.Size = New System.Drawing.Size(200, 585)
            Me.settingsPanel.Controls.SetChildIndex(Me.radGroupBox1, 0)
            '
            'radGridView1
            '
            Me.radGridView1.Dock = System.Windows.Forms.DockStyle.Fill
            Me.radGridView1.ForeColor = System.Drawing.Color.Black
            Me.radGridView1.Location = New System.Drawing.Point(0, 0)
            '
            'radGridView1
            '
            GridViewDecimalColumn1.DataType = GetType(Integer)
            GridViewDecimalColumn1.FieldName = "OrderID"
            GridViewDecimalColumn1.HeaderText = "OrderID"
            GridViewDecimalColumn1.IsAutoGenerated = True
            GridViewDecimalColumn1.Name = "OrderID"
            GridViewDecimalColumn2.DataType = GetType(Integer)
            GridViewDecimalColumn2.FieldName = "ProductID"
            GridViewDecimalColumn2.HeaderText = "ProductID"
            GridViewDecimalColumn2.IsAutoGenerated = True
            GridViewDecimalColumn2.Name = "ProductID"
            GridViewDecimalColumn3.FieldName = "UnitPrice"
            GridViewDecimalColumn3.HeaderText = "UnitPrice"
            GridViewDecimalColumn3.IsAutoGenerated = True
            GridViewDecimalColumn3.Name = "UnitPrice"
            GridViewDecimalColumn4.DataType = GetType(Short)
            GridViewDecimalColumn4.FieldName = "Quantity"
            GridViewDecimalColumn4.HeaderText = "Quantity"
            GridViewDecimalColumn4.IsAutoGenerated = True
            GridViewDecimalColumn4.Name = "Quantity"
            GridViewDecimalColumn5.DataType = GetType(Single)
            GridViewDecimalColumn5.FieldName = "Discount"
            GridViewDecimalColumn5.HeaderText = "Discount"
            GridViewDecimalColumn5.IsAutoGenerated = True
            GridViewDecimalColumn5.Name = "Discount"
            Me.radGridView1.MasterTemplate.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() {GridViewDecimalColumn1, GridViewDecimalColumn2, GridViewDecimalColumn3, GridViewDecimalColumn4, GridViewDecimalColumn5})
            Me.radGridView1.MasterTemplate.DataSource = Me.orderDetailsBindingSource
            Me.radGridView1.Name = "radGridView1"
            Me.radGridView1.Size = New System.Drawing.Size(1327, 929)
            Me.radGridView1.TabIndex = 1
            Me.radGridView1.ThemeName = "ControlDefault"
            '
            'orderDetailsBindingSource
            '
            Me.orderDetailsBindingSource.DataMember = "Order Details"
            Me.orderDetailsBindingSource.DataSource = Me.northwindDataSet
            '
            'northwindDataSet
            '
            Me.northwindDataSet.DataSetName = "NorthwindDataSet"
            Me.northwindDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
            '
            'order_DetailsTableAdapter
            '
            Me.order_DetailsTableAdapter.ClearBeforeFill = True
            '
            'radGroupBox1
            '
            Me.radGroupBox1.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping
            Me.radGroupBox1.Anchor = System.Windows.Forms.AnchorStyles.Top
            Me.radGroupBox1.Controls.Add(Me.radLabel1)
            Me.radGroupBox1.Controls.Add(Me.radSpinEditor2)
            Me.radGroupBox1.Controls.Add(Me.radSpinEditor1)
            Me.radGroupBox1.Controls.Add(Me.radComboBox3)
            Me.radGroupBox1.Controls.Add(Me.radComboBox2)
            Me.radGroupBox1.Controls.Add(Me.radComboBox1)
            Me.radGroupBox1.HeaderText = "Column restrictions:"
            Me.radGroupBox1.Location = New System.Drawing.Point(10, 46)
            Me.radGroupBox1.Name = "radGroupBox1"
            '
            '
            '
            Me.radGroupBox1.RootElement.Padding = New System.Windows.Forms.Padding(2, 18, 2, 2)
            Me.radGroupBox1.Size = New System.Drawing.Size(180, 190)
            Me.radGroupBox1.TabIndex = 1
            Me.radGroupBox1.Text = "Column restrictions:"
            Me.radGroupBox1.ThemeName = "ControlDefault"
            '
            'radLabel1
            '
            Me.radLabel1.Location = New System.Drawing.Point(17, 110)
            Me.radLabel1.Name = "radLabel1"
            Me.radLabel1.Size = New System.Drawing.Size(25, 18)
            Me.radLabel1.TabIndex = 5
            Me.radLabel1.Text = "and"
            '
            'radSpinEditor2
            '
            Me.radSpinEditor2.Location = New System.Drawing.Point(17, 156)
            Me.radSpinEditor2.Name = "radSpinEditor2"
            '
            '
            '
            Me.radSpinEditor2.RootElement.AutoSizeMode = Telerik.WinControls.RadAutoSizeMode.WrapAroundChildren
            Me.radSpinEditor2.Size = New System.Drawing.Size(78, 20)
            Me.radSpinEditor2.TabIndex = 4
            Me.radSpinEditor2.TabStop = False
            '
            'radSpinEditor1
            '
            Me.radSpinEditor1.Location = New System.Drawing.Point(17, 84)
            Me.radSpinEditor1.Name = "radSpinEditor1"
            '
            '
            '
            Me.radSpinEditor1.RootElement.AutoSizeMode = Telerik.WinControls.RadAutoSizeMode.WrapAroundChildren
            Me.radSpinEditor1.Size = New System.Drawing.Size(78, 20)
            Me.radSpinEditor1.TabIndex = 3
            Me.radSpinEditor1.TabStop = False
            '
            'radComboBox3
            '
            Me.radComboBox3.DropDownStyle = Telerik.WinControls.RadDropDownStyle.DropDownList
            Me.radComboBox3.Location = New System.Drawing.Point(17, 130)
            Me.radComboBox3.Name = "radComboBox3"
            Me.radComboBox3.Size = New System.Drawing.Size(147, 20)
            Me.radComboBox3.TabIndex = 2
            Me.radComboBox3.Text = "radComboBox3"
            '
            'radComboBox2
            '
            Me.radComboBox2.DropDownStyle = Telerik.WinControls.RadDropDownStyle.DropDownList
            Me.radComboBox2.Location = New System.Drawing.Point(17, 58)
            Me.radComboBox2.Name = "radComboBox2"
            Me.radComboBox2.Size = New System.Drawing.Size(147, 20)
            Me.radComboBox2.TabIndex = 1
            Me.radComboBox2.Text = "radComboBox2"
            '
            'radComboBox1
            '
            Me.radComboBox1.DropDownStyle = Telerik.WinControls.RadDropDownStyle.DropDownList
            Me.radComboBox1.Location = New System.Drawing.Point(17, 32)
            Me.radComboBox1.Name = "radComboBox1"
            Me.radComboBox1.Size = New System.Drawing.Size(147, 20)
            Me.radComboBox1.TabIndex = 0
            Me.radComboBox1.Text = "radComboBox1"
            '
            'Form1
            '
            Me.Controls.Add(Me.radGridView1)
            Me.Name = "Form1"
            Me.Size = New System.Drawing.Size(1337, 939)
            Me.Controls.SetChildIndex(Me.radGridView1, 0)
            Me.Controls.SetChildIndex(Me.settingsPanel, 0)
            CType(Me.settingsPanel, System.ComponentModel.ISupportInitialize).EndInit()
            Me.settingsPanel.ResumeLayout(False)
            Me.settingsPanel.PerformLayout()
            CType(Me.radGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.orderDetailsBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.northwindDataSet, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.radGroupBox1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.radGroupBox1.ResumeLayout(False)
            Me.radGroupBox1.PerformLayout()
            CType(Me.radLabel1, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.radSpinEditor2, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.radSpinEditor1, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.radComboBox3, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.radComboBox2, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.radComboBox1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.ResumeLayout(False)

        End Sub

		#End Region

		Private radGridView1 As Telerik.WinControls.UI.RadGridView
		Private northwindDataSet As Telerik.Examples.WinControls.DataSources.NorthwindDataSet
		Private orderDetailsBindingSource As BindingSource
		Private order_DetailsTableAdapter As Telerik.Examples.WinControls.DataSources.NorthwindDataSetTableAdapters.Order_DetailsTableAdapter
		Private radGroupBox1 As Telerik.WinControls.UI.RadGroupBox
		Private radComboBox1 As Telerik.WinControls.UI.RadDropDownList
		Private radComboBox3 As Telerik.WinControls.UI.RadDropDownList
		Private radComboBox2 As Telerik.WinControls.UI.RadDropDownList
		Private radSpinEditor1 As Telerik.WinControls.UI.RadSpinEditor
		Private radSpinEditor2 As Telerik.WinControls.UI.RadSpinEditor
		Private radLabel1 As Telerik.WinControls.UI.RadLabel
	End Class
End Namespace
