'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _double() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_double", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property Anna() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Anna", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property Background() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property blue_grey_green_small() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("blue_grey_green_small", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property Bobby() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Bobby", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property calendar() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property clean() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("clean", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property Clock() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Clock", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property clock_small() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("clock_small", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property default_small() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("default_small", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property double_user_blue() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("double_user_blue", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property double_user_green() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("double_user_green", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property double_user_grey() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("double_user_grey", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property double_user_orange() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("double_user_orange", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property double_user_red() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("double_user_red", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property double_users() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("double_users", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property edit() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property family() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("family", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property family_user_blue() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("family_user_blue", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property family_user_green() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("family_user_green", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property family_user_grey() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("family_user_grey", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property family_user_orange() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("family_user_orange", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property family_user_red() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("family_user_red", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property family_users() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("family_users", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property fasha_borders() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("fasha_borders", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property fasha_no_borders() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("fasha_no_borders", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property fasha_no_borders_fullsize() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("fasha_no_borders_fullsize", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property free_room() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("free_room", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property free_room_bluegrey() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("free_room_bluegrey", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property free_room_pink() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("free_room_pink", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property free_room_teal() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("free_room_teal", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property GlyphArrowChevronLeft() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GlyphArrowChevronLeft", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property GlyphArrowChevronRight() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GlyphArrowChevronRight", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property GlyphCalendar_small() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GlyphCalendar_small", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property GlyphCheck_small() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GlyphCheck_small", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property GlyphClose() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GlyphClose", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property GlyphWrench() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GlyphWrench", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property ic_done_white96_circle() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ic_done_white96_circle", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property ic_gavel_black_18dp_1x_grey96() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ic_gavel_black_18dp_1x_grey96", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property ic_timelapse_black_18dp_1x_grey96() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ic_timelapse_black_18dp_1x_grey96", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property Millie() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Millie", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property not_clean() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("not_clean", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property pink_blue_small() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("pink_blue_small", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property plus() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property repair() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("repair", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property repair_small() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("repair_small", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend ReadOnly Property Roboto_Medium() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("Roboto_Medium", resourceCulture)
				Return (CType(obj, Byte()))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property search() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property [single]() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("single", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property single_user() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("single_user", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property single_user_blue() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("single_user_blue", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property single_user_green() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("single_user_green", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property single_user_grey() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("single_user_grey", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property single_user_orange() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("single_user_orange", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property single_user_red() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("single_user_red", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property stars() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("stars", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		''' </summary>
		Friend ReadOnly Property starsIcon() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("starsIcon", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property teal_red_small() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("teal_red_small", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property tripple() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("tripple", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property tripple_user_blue() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("tripple_user_blue", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property tripple_user_green() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("tripple_user_green", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property tripple_user_grey() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("tripple_user_grey", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property tripple_user_orange() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("tripple_user_orange", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property tripple_user_red() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("tripple_user_red", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property tripple_users() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("tripple_users", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property
	End Module
End Namespace
