
CREATE database OnYourWeddingDay
USE OnYourWeddingDay
go

CREATE TABLE nhanvien(
	id INT IDENTITY(1,1) PRIMARY KEY,
	Hoten VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Pass VARCHAR(100) NOT NULL,
	Gender VARCHAR(500),
	Pic VARBINARY(MAX),
	Phone INT,
	Addre VARCHAR(150),
	CMND INT UNIQUE,
	Birth DATE,
	Descrip VARCHAR(500),
	MaChucVu int,
	Regency VARCHAR(100),
	Salary DECIMAL(9,0),
	is_blocked BIT ,
	is_reported BIT,
	create_at DATETIME,
	FOREIGN KEY (MaChucVu) REFERENCES ChucVu (MaChucVu)
)

CREATE TABLE USER_CONTACT (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	USER_ID INT,
	CONTACT_ID INT,
	FULLNAME VARCHAR(100),
	CREATE_AT DATETIME,

	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id),
	FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (ID)
)

CREATE TABLE CONTACT (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FULLNAME VARCHAR(100),
	PHONE INT,
	EMAILS VARCHAR(255),
	CREATE_AT DATETIME
)

CREATE TABLE ChucVu(
	MaChucVu INT IDENTITY(1,1) PRIMARY KEY,
	ChucVu VARCHAR(50),
)

CREATE TABLE DEVICE (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	USER_ID INT,
	DEVICE_ID INT,
	DEVICE_TOKEN VARCHAR(120),
	CREATE_AT DATETIME,
	UPDATE_AT DATETIME

	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id)
)

CREATE TABLE ACCESS (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	USER_ID INT,
	DEVICE_ID INT,
	TOKEN VARCHAR(60),
	CREATE_AT DATETIME,
	UPDATE_AT DATETIME

	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id),
	FOREIGN KEY (DEVICE_ID) REFERENCES dbo.DEVICE (ID)
)

CREATE TABLE CONVERSATIONS (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	USER_ID INT, --CREATOR_ID
	TITLE VARCHAR(255),
	CHANNEL_ID VARCHAR(255),
	CREATE_AT DATETIME,
	UPDATE_AT DATETIME,
	DELETE_AT DATETIME

	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id)
)

CREATE TABLE PARTICIPANT (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	CONVERSATIONS_ID INT,
	USER_ID INT,
	CREATE_AT DATETIME,
	UPDATE_AT DATETIME

	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id),
	FOREIGN KEY (CONVERSATIONS_ID) REFERENCES dbo.CONVERSATIONS (ID)
)

CREATE TABLE BLOCK_LIST (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	USER_ID INT,
	PARTICIPANT_ID INT,
	CREATE_AT DATETIME

	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id),
	FOREIGN KEY (PARTICIPANT_ID) REFERENCES dbo.PARTICIPANT (ID)
)

CREATE TABLE USER_VERIFICATION (
	USER_ID INT,
	VERIFICATION_CODE VARCHAR(45),
	CREATE_AT DATETIME

	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id)
)

CREATE TABLE REPORT (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	USER_ID INT,
	PARTICIPANT_ID INT,
	REPORT_TYPE VARCHAR(45),
	NOTES TEXT,
	CREATE_AT DATETIME

	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id),
	FOREIGN KEY (PARTICIPANT_ID) REFERENCES dbo.PARTICIPANT (ID)
)

CREATE TABLE DELETE_CONVERSATION (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	CONVERSATION_ID INT,
	USER_ID INT,
	CREATE_AT DATETIME

	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id),
	FOREIGN KEY (CONVERSATION_ID) REFERENCES dbo.CONVERSATIONS (
ID)
)

CREATE TABLE MESSAGES (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	CONVERSATION_ID INT,
	USER_ID INT, -- SENDER_ID
	GUILD VARCHAR(100),
	MESSAGES VARCHAR(455),
	CREATE_AT DATETIME,
	UPDATE_AT DATETIME

	FOREIGN KEY (CONVERSATION_ID) REFERENCES dbo.CONVERSATIONS (ID),
	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id)
)

CREATE TABLE DELETE_MESSAGE (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	MESS_ID INT,
	USER_ID INT,
	CREATE_AT DATETIME,
	UPDATE_AT DATETIME
	
	FOREIGN KEY (MESS_ID) REFERENCES dbo.MESSAGES (ID),
	FOREIGN KEY (USER_ID) REFERENCES dbo.nhanvien (id)
)

CREATE TABLE ATTACHMENT (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MESSAGE_ID INT,
	THUMP_URL VARCHAR(455),
	FILE_URL VARCHAR(455),
	CREATE_AT DATETIME,
	UPDATE_AT DATETIME

	FOREIGN KEY (MESSAGE_ID) REFERENCES dbo.MESSAGES (ID)
)






BEGIN -- TRIGER AND STORE PROCDURE

	CREATE TRIGGER LuongChucVu ON nhanvien
	AFTER INSERT
	AS
	BEGIN 
	DECLARE @id INT
	DECLARE @Machuvu INT
	DECLARE @luong INT
		SELECT @Machuvu = machucvu FROM dbo.ChucVu
		SELECT MaChucVu , @luong = luong FROM inserted WHERE MaChucVu = @Machuvu
		UPDATE dbo.nhanvien SET luong = @luong * 10 WHERE MaChucVu = 1
		UPDATE dbo.nhanvien SET luong = @luong * 9 WHERE MaChucVu = 2
		UPDATE dbo.nhanvien SET luong = @luong * 8 WHERE MaChucVu = 3
		UPDATE dbo.nhanvien SET luong = @luong * 7 WHERE MaChucVu = 4
		UPDATE dbo.nhanvien SET luong = @luong * 6 WHERE MaChucVu = 5
		UPDATE dbo.nhanvien SET luong = @luong * 5 WHERE MaChucVu = 6
		UPDATE dbo.nhanvien SET luong = @luong * 4 WHERE MaChucVu = 7
		UPDATE dbo.nhanvien SET luong = @luong * 3 WHERE MaChucVu = 8
		UPDATE dbo.nhanvien SET luong = @luong * 2 WHERE MaChucVu = 9
	END

	create proc getaccount
	@emails VARCHAR(100), @password varchar(100)
	as
	Begin
		select * FROM dbo.nhanvien WHERE Email = @emails AND Pass = @password
	END

	create proc Inste
	@emails varchar(100),
	@name varchar (100),
	@pass varchar(100)
	as
	begin
		insert into nhanvien (Hoten,Email,Pass) VALUES (@name , @emails , @pass)
	END

	create proc getaccount
	@emails varchar (100), @pass varchar(100)
	AS BEGIN
		SELECT * FROM dbo.nhanvien WHERE Email = @emails AND Pass = @pass
	END
END

BEGIN --SQL Execute
	BEGIN -- TAKE OUT ACCOUNT TO LOGIN
		Exec dbo.getaccount @emails = N'hermonie023@cs.kevart.com' , @pass = N'emma021021' 
		Exec dbo.getaccount @emails = N'hermonie023@cs.kevart.com' , @pass = N'emma021021'
		SELECT * FROM dbo.nhanvien WHERE Email = N'hermonie023@cs.kevart.com' AND Pass = N'emma021021'
	END
END

BEGIN -- Insert Data 
	BEGIN --INSERT DATA NHANVIEN
		INSERT INTO dbo.nhanvien (Hoten,Email,Pass,Gender,Phone,Addre,CMND,Birth,Descrip, MaChucVu,Regency,Salary,is_blocked,is_reported,create_at,Pic)
		SELECT N'Emma Wattson', N'hermomie05@cs.kaviert.com' , N'emmawat0412112' , N'Female' , 083441564 , N'Pa-ri, France' , 196461313 ,'1990-4-15', N'I am a Good Girl' , '1', N'Designer', '45000000',0,0,'2017-7-10', BulkColumn FROM OPENROWSET(BULK 'D:\Lesson\RIT\C #\Winform\Raven\Database\Used\HuongDanVien\Emma2.jpg', SINGLE_BLOB) AS PICTURE
	END
	BEGIN --INSERT DATA CHUCVU
		INSERT INTO dbo.ChucVu
		(
			ChucVu
		)
		VALUES
		('Manager' -- ChucVu - varchar(50)
		)
		INSERT INTO dbo.ChucVu
		(
			ChucVu
		)
		VALUES
		('Deputy Manager' -- ChucVu - varchar(50)
			)
		INSERT INTO dbo.ChucVu
		(
			ChucVu
		)
		VALUES
		(
		'Receptionists' -- ChucVu - varchar(50)
		)
	END
END

BEGIN -- DROP TABLE
	DROP TABLE nhanvien
END