'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
Namespace My


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DiagramFirstLook.Properties.Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = Value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Ana_Trujilo() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Ana_Trujilo", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Andrew_Fuller() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Andrew_Fuller", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Brenda_Smith() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Brenda_Smith", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Elizabeth_Lincoln() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Elizabeth_Lincoln", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Georg_Pipps() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Georg_Pipps", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Hanna_Moos() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Hanna_Moos", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Janet_Levering() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Janet_Levering", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Janine_Labrune() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Janine_Labrune", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Jason_Roland() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Jason_Roland", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Jeremy_Boather() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Jeremy_Boather", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property John_Steel() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("John_Steel", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Karin_Josephs() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Karin_Josephs", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Karl_Jablonski() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Karl_Jablonski", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Laura_Callahan() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Laura_Callahan", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Margaret_Peacock() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Margaret_Peacock", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Marie_Bertrand() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Marie_Bertrand", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Martin_Sommer() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Martin_Sommer", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Mary_Saveley() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Mary_Saveley", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Nancy_Davolio() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Nancy_Davolio", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
		'''&lt;Root&gt;
		'''	&lt;Node Name=&quot;Management&quot; Branch=&quot;Management&quot;&gt;
		'''    &lt;NodeMember Name=&quot;Andrew Fuller&quot; Position=&quot;CEO&quot; /&gt;
		'''    &lt;NodeMember Name=&quot;Jason Roland&quot; Position=&quot;President&quot; /&gt;
		'''    &lt;Node Name=&quot;Development Dept.&quot; Branch=&quot;Development&quot;&gt;
		'''      &lt;NodeMember Name=&quot;Martin Sommer&quot; Position=&quot;Architect&quot; /&gt;
		'''      &lt;NodeMember Name=&quot;Jeremy Boather&quot; Position=&quot;Senior Team Lead&quot; /&gt;
		'''      &lt;NodeMember Name=&quot;John Steel&quot; Position=&quot;Development Manager&quot; /&gt;
		'''      &lt;NodeMember Name=&quot;Karin Jose [rest of string was truncated]&quot;;.
		''' </summary>
		Friend Shared ReadOnly Property Organization() As String
			Get
				Return ResourceManager.GetString("Organization", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Paula_Wilson() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Paula_Wilson", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Pedro_Alfonso() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Pedro_Alfonso", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Robert_King() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Robert_King", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property settingsBlack() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("settingsBlack", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Steven_Buchanan() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Steven_Buchanan", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Viktoria_Ashworth() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Viktoria_Ashworth", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Class
End Namespace
