Namespace Telerik.Examples.WinControls.GridView.Hierarchy.LoadOnDemandHierarchy
	Partial Public Class Form1
		''' <summary> 
		''' Required designer variable.
		''' </summary>
		Private components As System.ComponentModel.IContainer = Nothing

		''' <summary> 
		''' Clean up any resources being used.
		''' </summary>
		''' <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			If disposing AndAlso (components IsNot Nothing) Then
				components.Dispose()
			End If
			MyBase.Dispose(disposing)
		End Sub

		#Region "Component Designer generated code"

		''' <summary> 
		''' Required method for Designer support - do not modify 
		''' the contents of this method with the code editor.
		''' </summary>
		Private Sub InitializeComponent()
			Me.components = New System.ComponentModel.Container()
			Dim gridViewTextBoxColumn1 As New Telerik.WinControls.UI.GridViewTextBoxColumn()
			Dim gridViewTextBoxColumn3 As New Telerik.WinControls.UI.GridViewTextBoxColumn()
			Dim gridViewTextBoxColumn4 As New Telerik.WinControls.UI.GridViewTextBoxColumn()
			Dim gridViewTextBoxColumn5 As New Telerik.WinControls.UI.GridViewTextBoxColumn()
			Dim gridViewDecimalColumn1 As New Telerik.WinControls.UI.GridViewDecimalColumn()
			Dim gridViewTextBoxColumn6 As New Telerik.WinControls.UI.GridViewTextBoxColumn()
			Dim gridViewDecimalColumn2 As New Telerik.WinControls.UI.GridViewDecimalColumn()
			Dim gridViewDateTimeColumn1 As New Telerik.WinControls.UI.GridViewDateTimeColumn()
			Me.radGridView1 = New Telerik.WinControls.UI.RadGridView()
			Me.productModelBindingSource = New BindingSource(Me.components)
			Me.adventureLT2008DataSet = New Telerik.Examples.WinControls.DataSources.AdventureLT2008DataSet()
			Me.gridViewTemplate1 = New Telerik.WinControls.UI.GridViewTemplate()
			Me.productModelTableAdapter = New Telerik.Examples.WinControls.DataSources.AdventureLT2008DataSetTableAdapters.ProductModelTableAdapter()
			Me.productBindingSource = New BindingSource(Me.components)
			Me.productTableAdapter = New Telerik.Examples.WinControls.DataSources.AdventureLT2008DataSetTableAdapters.ProductTableAdapter()
			CType(Me.settingsPanel, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.productModelBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.adventureLT2008DataSet, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.gridViewTemplate1, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.productBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
			Me.SuspendLayout()
			' 
			' settingsPanel
			' 
			Me.settingsPanel.Location = New Point(1446, 1)
			Me.settingsPanel.Size = New Size(200, 770)
			' 
			' radGridView1
			' 
			Me.radGridView1.Dock = DockStyle.Fill
			Me.radGridView1.Location = New Point(0, 0)
			' 
			' radGridView1
			' 
			gridViewTextBoxColumn1.FieldName = "Name"
			gridViewTextBoxColumn1.FormatString = ""
			gridViewTextBoxColumn1.HeaderText = "Name"
			gridViewTextBoxColumn1.IsAutoGenerated = True
			gridViewTextBoxColumn1.Name = "Name"
			gridViewTextBoxColumn1.Width = 300
			Me.radGridView1.MasterTemplate.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() { gridViewTextBoxColumn1})
			Me.radGridView1.MasterTemplate.DataSource = Me.productModelBindingSource
			Me.radGridView1.MasterTemplate.Templates.AddRange(New Telerik.WinControls.UI.GridViewTemplate() { Me.gridViewTemplate1})
			Me.radGridView1.Name = "radGridView1"
			Me.radGridView1.Size = New Size(1647, 772)
			Me.radGridView1.TabIndex = 0
			Me.radGridView1.Text = "radGridView1"
			' 
			' productModelBindingSource
			' 
			Me.productModelBindingSource.DataMember = "ProductModel"
			Me.productModelBindingSource.DataSource = Me.adventureLT2008DataSet
			' 
			' adventureLT2008DataSet
			' 
			Me.adventureLT2008DataSet.DataSetName = "AdventureLT2008DataSet"
			Me.adventureLT2008DataSet.SchemaSerializationMode = SchemaSerializationMode.IncludeSchema
			' 
			' gridViewTemplate1
			' 
			gridViewTextBoxColumn3.FieldName = "Name"
			gridViewTextBoxColumn3.HeaderText = "Name"
			gridViewTextBoxColumn3.IsAutoGenerated = True
			gridViewTextBoxColumn3.Name = "Name"
			gridViewTextBoxColumn4.FieldName = "ProductNumber"
			gridViewTextBoxColumn4.HeaderText = "ProductNumber"
			gridViewTextBoxColumn4.IsAutoGenerated = True
			gridViewTextBoxColumn4.Name = "ProductNumber"
			gridViewTextBoxColumn5.FieldName = "Color"
			gridViewTextBoxColumn5.HeaderText = "Color"
			gridViewTextBoxColumn5.IsAutoGenerated = True
			gridViewTextBoxColumn5.Name = "Color"
			gridViewDecimalColumn1.FieldName = "ListPrice"
			gridViewDecimalColumn1.HeaderText = "ListPrice"
			gridViewDecimalColumn1.IsAutoGenerated = True
			gridViewDecimalColumn1.Name = "ListPrice"
			gridViewDecimalColumn1.TextAlignment = ContentAlignment.MiddleRight
			gridViewTextBoxColumn6.FieldName = "Size"
			gridViewTextBoxColumn6.HeaderText = "Size"
			gridViewTextBoxColumn6.IsAutoGenerated = True
			gridViewTextBoxColumn6.Name = "Size"
			gridViewDecimalColumn2.FieldName = "Weight"
			gridViewDecimalColumn2.HeaderText = "Weight"
			gridViewDecimalColumn2.IsAutoGenerated = True
			gridViewDecimalColumn2.Name = "Weight"
			gridViewDecimalColumn2.TextAlignment = ContentAlignment.MiddleRight
			gridViewDateTimeColumn1.FieldName = "DiscontinuedDate"
			gridViewDateTimeColumn1.HeaderText = "DiscontinuedDate"
			gridViewDateTimeColumn1.IsAutoGenerated = True
			gridViewDateTimeColumn1.Name = "DiscontinuedDate"
			Me.gridViewTemplate1.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() { gridViewTextBoxColumn3, gridViewTextBoxColumn4, gridViewTextBoxColumn5, gridViewDecimalColumn1, gridViewTextBoxColumn6, gridViewDecimalColumn2, gridViewDateTimeColumn1})
			' 
			' productModelTableAdapter
			' 
			Me.productModelTableAdapter.ClearBeforeFill = True
			' 
			' productBindingSource
			' 
			Me.productBindingSource.DataMember = "Product"
			Me.productBindingSource.DataSource = Me.adventureLT2008DataSet
			' 
			' productTableAdapter
			' 
			Me.productTableAdapter.ClearBeforeFill = True
			' 
			' Form1
            ' 
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
			Me.Controls.Add(Me.radGridView1)
			Me.Name = "Form1"
			Me.Size = New Size(1647, 772)

			Me.Controls.SetChildIndex(Me.radGridView1, 0)
			Me.Controls.SetChildIndex(Me.settingsPanel, 0)
			CType(Me.settingsPanel, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.productModelBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.adventureLT2008DataSet, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.gridViewTemplate1, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.productBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
			Me.ResumeLayout(False)

		End Sub

		#End Region

		Private radGridView1 As Telerik.WinControls.UI.RadGridView
		Private productModelBindingSource As BindingSource
		Private adventureLT2008DataSet As DataSources.AdventureLT2008DataSet
		Private productModelTableAdapter As DataSources.AdventureLT2008DataSetTableAdapters.ProductModelTableAdapter
		Private productBindingSource As BindingSource
		Private productTableAdapter As DataSources.AdventureLT2008DataSetTableAdapters.ProductTableAdapter
		Private gridViewTemplate1 As Telerik.WinControls.UI.GridViewTemplate

	End Class
End Namespace
